-
  id:
    '23'
  type:
    カジュアルトーク
  name:
    第23回 カジュアルトーク
  date:
    '2017-04-28'
  image:
    '23.jpg'
  link:
    '23/'

-
  id:
    '22'
  type:
    カジュアルトーク
  name:
    第22回 カジュアルトーク
  date:
    '2017-03-31'
  image:
    '22.jpg'
  link:
    '22/'

-
  id:
    '21'
  type:
    カジュアルトーク
  name:
    第21回 カジュアルトーク
  date:
    '2017-03-20'
  image:
    '21.jpg'
  link:
    '21/'

-
  id:
    '20'
  type:
    カジュアルトーク
  name:
    第20回 カジュアルトーク
  date:
    '2017-01-31'
  image:
    '20.jpg'
  link:
    '20/'

-
  id:
    'new-year-party-2017'
  type:
    新年会
  name:
    2017年 WBA若手の会 新年会
  date:
    '2017-01-28'
  image:
    'new-year-party-2017.jpg'
  link:
    'new-year-party-2017/'

-
  id:
    '19'
  type:
    カジュアルトーク
  name:
    第19回 カジュアルトーク
  date:
    '2016-11-30'
  image:
    '19.jpg'
  link:
    '19/'

-
  id:
    '18'
  type:
    カジュアルトーク
  name:
    第18回 カジュアルトーク
  date:
    '2016-11-22'
  image:
    '18.jpg'
  link:
    '18/'

-
  id:
    '17'
  type:
    カジュアルトーク
  name:
    第17回 カジュアルトーク
  date:
    '2016-11-12'
  image:
    '17.jpg'
  link:
    '17/'

-
  id:
    '16'
  type:
    カジュアルトーク
  name:
    第16回 カジュアルトーク
  date:
    '2016-07-29'
  image:
    '16.jpg'
  link:
    '16/'

-
  id:
    '15'
  type:
    勉強会
  name:
    第15回
  date:
    '2016-06-16'
  image:
    '15.jpg'
  link:
    '15/'

-
  id:
    '14'
  type:
    カジュアルトーク
  name:
    第14回 カジュアルトーク
  date:
    '2016-06-04'
  image:
    '14.jpg'
  link:
    '14/'

-
  id:
    'data-2'
  type:
    データ解析くらぶ
  name:
    第2回 データ解析くらぶ
  date:
    '2016-05-21'
  image:
    'data-2.jpg'
  link:
    'data-2/'

-
  id:
    'data-1'
  type:
    データ解析くらぶ
  name:
    第1回 データ解析くらぶ
  date:
    '2016-04-16'
  image:
    'data-1.jpg'
  link:
    'data-1/'

-
  id:
    'spring-meetup-2016'
  type:
    懇親会
  name:
    2016年 春の交流会
  date:
    '2016-04-23'
  image:
    'spring-meetup-2016.jpg'
  link:
    'spring-meetup-2016/'

-
  id:
    '13'
  type:
    勉強会
  name:
    第13回
  date:
    '2016-03-08'
  image:
    '13.jpg'
  link:
    '13/'

-
  id:
    'girls-2'
  type:
    女子会
  name:
    第2回 WBA若手の会　女子会＠下北沢
  date:
    '2016-02-11'
  image:
    'girls-2.jpg'
  link:
    'girls-2/'

-
  id:
    '12'
  type:
    カジュアルトーク
  name:
    第12回 カジュアルトーク
  date:
    '2016-02-07'
  image:
    '12.jpg'
  link:
    '12/'

-
  id:
    'new-year-party-2016'
  type:
    新年会
  name:
    2016年 WBA若手の会 新年会
  date:
    '2016-01-09'
  image:
    'new-year-party-2016.jpg'
  link:
    'new-year-party-2016/'

-
  id:
    'girls-1'
  type:
    女子会
  name:
    第1回 WBA若手の会　女子会＠新宿
  date:
    '2015-12-10'
  image:
    'girls-1.jpg'
  link:
    'girls-1/'

-
  id:
    'hackathon-1-report'
  type:
    ハッカソン
  name:
    第1回WBAIハッカソン活動報告
  date:
    '2015-12-10'
  image:
    'hackathon-1-report.jpg'
  link:
    'hackathon-1-report/'

-
  id:
    '11'
  type:
    勉強会
  name:
    第11回
  date:
    '2015-11-19'
  image:
    '11.jpg'
  link:
    '11/'

-
  id:
    '10'
  type:
    勉強会
  name:
    第10回
  date:
    '2015-10-14'
  image:
    '10.jpg'
  link:
    '10/'

-
  id:
    '9'
  type:
    カジュアルトーク
  name:
    第9回 カジュアルトーク
  date:
    '2015-10-12'
  image:
    '9.jpg'
  link:
    '9/'

-
  id:
    'hackathon-1'
  type:
    ハッカソン
  name:
    第1回WBAIハッカソン
  date:
    '2015-09-19'
  image:
    'hackathon-1.jpg'
  link:
    'hackathon-1/'

-
  id:
    'ideathon-1'
  type:
    ハッカソン
  name:
    第1回WBAIハッカソン アイデアソン
  date:
    '2015-09-19'
  image:
    'ideathon-1.jpg'
  link:
    'ideathon-1/'

-
  id:
    '8'
  type:
    勉強会
  name:
    第8回
  date:
    '2015-07-13'
  image:
    '8.jpg'
  link:
    '8/'

-
  id:
    '7'
  type:
    勉強会
  name:
    第7回
  date:
    '2015-06-29'
  image:
    '7.jpg'
  link:
    '7/'

-
  id:
    '6'
  type:
    勉強会
  name:
    第6回
  date:
    '2015-03-18'
  image:
    '6.jpg'
  link:
    '6/'

-
  id:
    '5'
  type:
    勉強会
  name:
    第5回
  date:
    '2015-03-05'
  link:
    '5/'

-
  id:
    '4'
  type:
    勉強会
  name:
    第4回
  date:
    '2014-11-13'
  link:
    '4/'

-
  id:
    '3'
  type:
    勉強会
  name:
    第3回
  date:
    '2014-11-13'
  link:
    '3/'

-
  id:
    '2'
  type:
    勉強会
  name:
    第2回
  date:
    '2014-10-23'
  link:
    '2/'

-
  id:
    '1'
  type:
    勉強会
  name:
    第1回
  date:
    '2014-10-09'
  link:
    '1/'

# -
#   id:
#   type:
#   name:
#   date:
#   image:
#   link:
