-
  type:
    カジュアルトーク
  name:
    第23回 カジュアルトーク
  date:
    '2017-04-28'
  image:
    '23.jpg'
  link:
    '23/'

-
  type:
    カジュアルトーク
  name:
    第22回 カジュアルトーク
  date:
    '2017-03-31'
  image:
    '22.jpg'
  link:
    '22/'

-
  type:
    カジュアルトーク
  name:
    第21回 カジュアルトーク
  date:
    '2017-03-20'
  image:
    '21.jpg'
  link:
    '21/'

-
  type:
    カジュアルトーク
  name:
    第20回 カジュアルトーク
  date:
    '2017-01-31'
  image:
    '20.jpg'
  link:
    '20/'

-
  type:
    新年会
  name:
    2017年 WBA若手の会 新年会
  image:
    'new-year-party-2017.jpg'
  link:
    'new-year-party-2017/'

-
  type:
    カジュアルトーク
  name:
    第19回 カジュアルトーク
  image:
    '19.jpg'
  link:
    '19/'

-
  type:
    カジュアルトーク
  name:
    第18回 カジュアルトーク
  image:
    '18.jpg'
  link:
    '18/'

-
  type:
    カジュアルトーク
  name:
    第17回 カジュアルトーク
  image:
    '17.jpg'
  link:
    '17/'

-
  type:
    カジュアルトーク
  name:
    第16回 カジュアルトーク
  image:
    '16.jpg'
  link:
    '16/'

-
  type:
    勉強会
  name:
    第15回
  image:
    '15.jpg'
  link:
    '15/'

-
  type:
    カジュアルトーク
  name:
    第14回 カジュアルトーク
  image:
    '14.jpg'
  link:
    '14/'

-
  type:
    データ解析くらぶ
  name:
    第2回 データ解析くらぶ
  image:
    'data-2.jpg'
  link:
    'data-2/'

-
  type:
    データ解析くらぶ
  name:
    第1回 データ解析くらぶ
  image:
    'data-1.jpg'
  link:
    'data-1/'

-
  type:
    懇親会
  name:
    2016年 春の交流会
  image:
    'spring-meetup-2016.jpg'
  link:
    'spring-meetup-2016/'

-
  type:
    勉強会
  name:
    第13回
  image:
    '13.jpg'
  link:
    '13/'

-
  type:
    女子会
  name:
    第2回 WBA若手の会　女子会＠下北沢
  image:
    'girls-2.jpg'
  link:
    'girls-2/'

-
  type:
    カジュアルトーク
  name:
    第12回 カジュアルトーク
  image:
    '12.jpg'
  link:
    '12/'

-
  type:
    新年会
  name:
    2016年 WBA若手の会 新年会
  image:
    'new-year-party-2016.jpg'
  link:
    'new-year-party-2016/'

-
  type:
    女子会
  name:
    第1回 WBA若手の会　女子会＠新宿
  image:
    'girls-1.jpg'
  link:
    'girls-1/'

-
  type:
    ハッカソン
  name:
    第1回WBAIハッカソン活動報告
  image:
    'hackathon-1-report.jpg'
  link:
    'hackathon-1-report/'

-
  type:
    勉強会
  name:
    第11回
  image:
    '11.jpg'
  link:
    '11/'

-
  type:
    勉強会
  name:
    第10回
  image:
    '10.jpg'
  link:
    '10/'

-
  type:
    カジュアルトーク
  name:
    第9回 カジュアルトーク
  image:
    '9.jpg'
  link:
    '9/'

-
  type:
    ハッカソン
  name:
    第1回WBAIハッカソン
  image:
    'hackathon-1.jpg'
  link:
    'hackathon-1/'

-
  type:
    ハッカソン
  name:
    第1回WBAIハッカソン アイデアソン
  image:
    'ideathon-1.jpg'
  link:
    'ideathon-1/'

-
  type:
    勉強会
  name:
    第8回
  image:
    '8.jpg'
  link:
    '8/'

-
  type:
    勉強会
  name:
    第7回
  image:
    '7.jpg'
  link:
    '7/'

-
  type:
    勉強会
  name:
    第6回
  image:
    '6.jpg'
  link:
    '6/'

-
  type:
    勉強会
  name:
    第5回
  link:
    '5/'

-
  type:
    勉強会
  name:
    第4回
  link:
    '4/'

-
  type:
    勉強会
  name:
    第3回
  link:
    '3/'

-
  type:
    勉強会
  name:
    第2回
  link:
    '2/'

-
  type:
    勉強会
  name:
    第1回
  link:
    '1/'

# -
#   type:
#   name:
#   date:
#   image:
#   link:
