normal:
  -
    name:
      大澤 正彦
    nameSub:
      Osawa Masahiko
    position:
      代表
    status:
      慶應義塾大学 D1
    image:
      'https://i0.wp.com/wbawakate.jp/wp-content/uploads/2015/01/osawa_wba-e1421331313884.jpg?fit=300%2C300'
    link:
      'member/osawa-masahiko.html'

  -
    name:
      坂井 美帆
    nameSub:
      Sakai Miho
    position:
      副代表
    image:
      'https://i0.wp.com/wbawakate.jp/wp-content/uploads/2016/03/photo2.jpg?fit=354%2C354'

  -
    name:
      島田 大樹
    nameSub:
      Shimada Daiki
    position:
      副代表
    status:
      法政大学大学院 修士2年
    image:
      'https://i1.wp.com/wbawakate.jp/wp-content/uploads/2015/02/shimada_daiki-e1423017064679.jpg?fit=300%2C300'

blockChain:
  -
    name:
      小松 昌憲
    nameSub:
      Komatsu Masatoshi
    position:
      ブロックチェーン支部　代表
    image:
      '//placehold.jp/360x360.png'
    link:
      'member/komatsu-masatoshi.html'

society:
  -
    name:
      芦原 佑太
    nameSub:
      Ashihara Yuta
    position:
      社会人支部　代表
    image:
      'https://i0.wp.com/wbawakate.jp/wp-content/uploads/2015/01/Screen-Shot-0027-01-31-at-23.27.36-e1425284535567.png?fit=300%2C300'

  -
    name:
      岩淵 勇樹
    nameSub:
      Iwabuchi Yuuki
    image:
      'https://i0.wp.com/wbawakate.jp/wp-content/uploads/2016/03/IMGP0596.jpg2_.jpg?fit=460%2C460'
    link:
      'member/iwabuchi-yuuki.html'

#  -
#    name:
#    nameSub:
#    position:
#    status:
#    link:
