normal:
  -
    name:
      大澤 正彦
    nameSub:
      Osawa Masahiko
    position:
      代表
    status:
      慶應義塾大学 D1
    image:
      'osawa-masahiko.jpg'
    link:
      'osawa-masahiko/'

  -
    name:
      坂井 美帆
    nameSub:
      Sakai Miho
    position:
      副代表
    image:
      'sakai-miho.jpg'
    link:
      'sakai-miho/'

  -
    name:
      島田 大樹
    nameSub:
      Shimada Daiki
    position:
      副代表
    status:
      法政大学大学院 修士2年
    image:
      'shimada-daiki.jpg'
    link:
      'shimada-daiki/'

kanto:
  -
    name:
      八木 拓真
    nameSub:
      Yagi Takuma
    position:
      東京工業大学
      工学部4年
    status:
      関東支部代表
    image:
      'yagi-takuma.jpg'
    link:
      'yagi-takuma/'

  -
    name:
      松岡 佑磨
    nameSub:
      Matsuoka Yuma
    position:
      法政大学
      理工学部4年
    status:
      関東支部副代表
    image:
      'matsuoka-yuma.jpg'
    link:
      'matsuoka-yuma/'

kansai:
  -
    name:
      西田 圭吾
    nameSub:
      Nishida Keigo
    position:
      関西支部代表
    status:
      大阪大学学部4年
    image:
      'nishida-keigo.jpg'
    link:
      'nishida-keigo/'

  -
    name:
      都築拓
    nameSub:
      Tsuzuki Taku
    position:
      関西支部副代表
    status:
      大阪大学学部4年
    image:
      'tsuzuki-taku.jpg'
    link:
      'tsuzuki-taku/'

blockChain:
  -
    name:
      小松 昌憲
    nameSub:
      Komatsu Masatoshi
    position:
      ブロックチェーン支部　代表
    image:
      '//placehold.jp/360x360.png'
    link:
      'komatsu-masatoshi/'

society:
  -
    name:
      芦原 佑太
    nameSub:
      Ashihara Yuta
    position:
      社会人支部　代表
    image:
      'ashihara-yuta.jpg'
    link:
      'ashihara-yuta/'

  -
    name:
      岩淵 勇樹
    nameSub:
      Iwabuchi Yuki
    image:
      'iwabuchi-yuki.jpg'
    link:
      'iwabuchi-yuki/'

#  -
#    name:
#    nameSub:
#    position:
#    status:
#    image:
#    link:
