normal:
  -
    name:
      大澤 正彦
    nameSub:
      Osawa Masahiko
    position:
      代表
    status:
      慶應義塾大学 D1
    image:
      'osawa-masahiko.jpg'
    link:
      'osawa-masahiko/'

  -
    name:
      坂井 美帆
    nameSub:
      Sakai Miho
    position:
      副代表
    image:
      'sakai-miho.jpg'
    link:
      'sakai-miho/'

  -
    name:
      島田 大樹
    nameSub:
      Shimada Daiki
    position:
      副代表
    status:
      法政大学大学院 
      修士2年
    image:
      'shimada-daiki.jpg'
    link:
      'shimada-daiki/'
      
  -
    name:
      川崎 雄介
    nameSub:
      Kawasaki Yusuke
    position:
      会計
    status:
      法政大学大学院 
      修士2年
    image:
      'kawasaki-yusuke.jpg'
    link:
      'kawasaki-yusuke/'
      
kanto:
  -
    name:
      八木 拓真
    nameSub:
      Yagi Takuma
    position:
      関東支部代表 
    status:
      東京工業大学
      工学部4年 
    image:
      'yagi-takuma.jpg'
    link:
      'yagi-takuma/'

  -
    name:
      松岡 佑磨
    nameSub:
      Matsuoka Yuma
    position:
      関東支部副代表
    status:
      法政大学
      理工学部4年   
    image:
      'matsuoka-yuma.jpg'
    link:
      'matsuoka-yuma/'

  -
    name:
      板谷 琴音
    nameSub:
      Itaya Kotone
    satatus:
      慶應義塾大学
      政策・メディア研究科2年
    image:
      'itaya-kotone.jpg'
    link:
      'itaya-kotone/'
      
  -
    name:
      加治屋 里奈
    nameSub:
      Kajiya Rina 
    satatus:
      法政大学
      理工学部4年
    image:
      'kajiya-rina.jpg'
    link:
      'kajiya-rina/'
      
  -
    name:
      神野 成海
    nameSub:
      Kanno Narumi 
    satatus:
      東京理科大学
      理学部3年
    image:
      'kanno-narumi.jpg'
    link:
      'kanno-narumi/'
      
  -
    name:
      佐藤 太一
    nameSub:
      Sato Taichi 
    satatus:
      東京都市大学付属高校
      3年
    image:
      'sato-taichi.jpg'
    link:
      'sato-taichi/'
      
  -
    name:
      竹田 卓也
    nameSub:
      Takeda Takuya 
    satatus:
      電気通信大学
    image:
      'takeda-takuya.jpg'
    link:
      'takeda-takuya/'
      
  -
    name:
      土井 ゆりか
    nameSub:
      Doi Yurika 
    satatus:
      東京大学
      工学部4年
    image:
      'doi-yurika.jpg'
    link:
      'doi-yurika/'
      
  -
    name:
      中村 健太郎
    nameSub:
      Nakamura Kentaro 
    satatus:
      慶應義塾大学
    image:
      'nakamura-kentaro.jpg'
    link:
      'nakamura-kentaro/'      
      
  -
    name:
      中村 晃貴
    nameSub:
      Nakamura Koki 
    satatus:
      慶應義塾大学
      理工学研究科修士1年
    image:
      'nakamura-koki.jpg'
    link:
      'nakamura-koki/' 
      
  -
    name:
      永田 祥平
    nameSub:
      Nagata Shohei 
    satatus:
      慶應義塾大学
      環境情報学部2年
    image:
      'nagata-shohei.jpg'
    link:
      'nagata-shohei/'      
      
  -
    name:
      原衛 直子
    nameSub:
      Harae Naoko 
    satatus:
      慶應義塾大学
      文学部4年
    image:
      'harae-naoko.jpg'
    link:
      'harae-naoko/'      
 
  -
    name:
      藤田 恵梨香
    nameSub:
      Fujita Erika 
    satatus:
      法政大学
      大学院修士1年
    image:
      'fujita-erika.jpg'
    link:
      'fujita-erika/'      
 
  -
    name:
      増山 七海
    nameSub:
      Masuyama Nanami 
    satatus:
      慶應義塾大学
      環境情報学部3年
    image:
      'masuyama-nanami.jpg'
    link:
      'masuyama-nanami/'      
 
  -
    name:
      金光 俊輔
    nameSub:
      Kanemitsu Shunsuke 
    satatus:
      慶應義塾大学大学院
      理工学研究科　修士2年
    image:
      'kanemitsu-shunsuke.jpg'
    link:
      'kanemitsu-shunsuke/' 
      
  -
    name:
      奥岡 耕平
    nameSub:
      Okuoka Kohei 
    satatus:
      慶應義塾大学
     　理工学部4年
    image:
      'okuoka-kohei.jpg'
    link:
      'okuoka-kohei/'     
      
kansai:
  -
    name:
      西田 圭吾
    nameSub:
      Nishida Keigo
    position:
      関西支部代表
    status:
      大阪大学
      学部4年
    image:
      'nishida-keigo.jpg'
    link:
      'nishida-keigo/'

  -
    name:
      都築拓
    nameSub:
      Tsuzuki Taku
    position:
      関西支部副代表
    status:
      大阪大学
      学部4年
    image:
      'tsuzuki-taku.jpg'
    link:
      'tsuzuki-taku/'

  -
    name:
      上乃 聖
    nameSub:
      Ueno Sei 
    satatus:
      同志社大学
      理工学部 情報システムデザイン学科3年
    image:
      'ueno-sei.jpg'
    link:
      'ueno-sei/'      

  -
    name:
      三浦 拓也
    nameSub:
      Miura Takuya 
    position:
      関西支部会計
    satatus:
      大阪大学
      学部4年
    image:
      'miura-takuya.jpg'
    link:
      'miura-takuya/'  
      
  -
    name:
      田村 陵大
    nameSub:
      Tamura Ryota 
    satatus:
      同志社大学大学院
      医療情報システム研究室
      修士1年
    image:
      'tamura-ryota.jpg'
    link:
      'tamura-ryota/'      

  -
    name:
      清丸 寛一
    nameSub:
      Kiyomaru Hirokazu 
    satatus:
      同志社大学
      理工学部情報システムデザイン学科3年
    image:
      'kiyomaru-hirokazu.jpg'
    link:
      'kiyomaru-hirokazu/'

  -
    name:
      廣芝 和之
    nameSub:
      Hiroshiba Kazuyuki 
    satatus:
      奈良先端科学技術大学院大学
      バイオサイエンス研究科
    image:
      'hiroshiba-kazuyuki.jpg'
    link:
      'hiroshiba-kazuyuki/'

blockChain:
  -
    name:
      小松 昌憲
    nameSub:
      Komatsu Masatoshi
    position:
      ブロックチェーン支部　代表
    image:
      '//placehold.jp/360x360.png'
    link:
      'komatsu-masatoshi/'

society:
  -
    name:
      芦原 佑太
    nameSub:
      Ashihara Yuta
    position:
      社会人支部　代表
    image:
      'ashihara-yuta.jpg'
    link:
      'ashihara-yuta/'

  -
    name:
      柿原 祥之
    nameSub:
      Kakihara Yoshiyuki 
    position:
      社会人支部　副代表
    image:
      'kakihara-yoshiyuki.jpg'
    link:
      'kakihara-yoshiyuki/'

  -
    name:
      門前 一馬
    nameSub:
      Kadomae Kazuma 
    satatus:
      クリエイティブディレクター
    image:
      'kadomae-kazuma.jpg'
    link:
      'kadomae-kazuma/'

  -
    name:
      永山 大志
    nameSub:
      Nagayama Taishi
    image:
      'nagayama-taishi.jpg'
    link:
      'nagayama-taishi/'

  -
    name:
      岩淵 勇樹
    nameSub:
      Iwabuchi Yuki
    image:
      'iwabuchi-yuki.jpg'
    link:
      'iwabuchi-yuki/'


  -
    name:
      池谷 昌大
    nameSub:
      Ikeya Masao
    image:
      'ikeya-masao.jpg'
    link:
      'ikeya-masao/'   
      
  -
    name:
      高木 勇輔
    nameSub:
      Takagi Yusuke
    image:
      'takagi-yusuke.jpg'
    link:
      'takagi-yusuke/' 
      
  -
    name:
      久保 隆宏
    nameSub:
      Kubo Takahiro
    image:
      'kubo-takahiro.jpg'
    link:
      'kubo-takahiro/'    
      
  -
    name:
      渡會 恭平
    nameSub:
      Watatai Kyohei
    image:
      'watarai-kyohei.jpg'
    link:
      'watarai-kyohei/' 
      
  -
    name:
      吉田 雄紀
    nameSub:
      Yoshida Yuki
    image:
      'yoshida-yuki.jpg'
    link:
      'yoshida-yuki/' 
      
  -
    name:
      亀田 重幸
    nameSub:
      Kameda Shigeyuki
    image:
      'kameda-shigeyuki.jpg'
    link:
      'kameda-shigeyuki/'

adviser:
  -
    name:
      伊藤 宏章
    nameSub:
      Ito Hiroaki
    position:
      顧問
    image:
      'ito-hiroaki.jpg'
    link:
      'ito-hiroaki/'      
#  -
#    name:
#    nameSub:
#    position:
#    status:
#    image:
#    link:
