normal:
  -
    name:
      大澤 正彦
    nameSub:
      Osawa Masahiko
    position:
      代表
    status:
      慶應義塾大学 D1
    image:
      'osawa-masahiko.jpg'
    link:
      'osawa-masahiko/'

  -
    name:
      坂井 美帆
    nameSub:
      Sakai Miho
    position:
      副代表
    image:
      'sakai-miho.jpg'
    link:
      'sakai-miho/'

  -
    name:
      島田 大樹
    nameSub:
      Shimada Daiki
    position:
      副代表
    status:
      法政大学大学院 修士2年
    image:
      'shimada-daiki.jpg'
    link:
      'shimada-daiki/'

blockChain:
  -
    name:
      小松 昌憲
    nameSub:
      Komatsu Masatoshi
    position:
      ブロックチェーン支部　代表
    image:
      '//placehold.jp/360x360.png'
    link:
      'komatsu-masatoshi/'

society:
  -
    name:
      芦原 佑太
    nameSub:
      Ashihara Yuta
    position:
      社会人支部　代表
    image:
      'ashihara-yuta.jpg'
    link:
      'ashihara-yuta/'

  -
    name:
      岩淵 勇樹
    nameSub:
      Iwabuchi Yuuki
    image:
      'iwabuchi-yuuki.jpg'
    link:
      'iwabuchi-yuuki/'

#  -
#    name:
#    nameSub:
#    position:
#    status:
#    link:
