site_name: 全脳アーキテクチャ若手の会
description: 全脳アーキテクチャ若手の会は、脳や人工知能、そしてそれらが与える影響について興味がある、すべての方のためのコミュニティです。
keywords: []
url: http://wbawakate.jp/
facebook_app_id: 114814789107922
ogp_image_url: http://wbawakate.jp/ogp.png
link_contact: https://docs.google.com/forms/d/1EKz9bmU8ipH0oZObiJwsIBgh4l5ftQWBthXfKfAH1hY/viewform
