-
  time:
    '2017-07-14'
  update:
    'CircleCI通知テスト'

-
  time:
    '2017-07-04'
  update:
    'テスト4'

-
  time:
    '2017-06-05'
  update:
    'テスト3'

-
  time:
    '2017-06-05'
  update:
    'テスト2'

-
  time:
    '2017-06-05'
  update:
    'テスト'

-
  time:
    '2017-05-04'
  update:
    '<a href="http://wbawakate.jp/posts/events/23th/">【2017-04-28】　「第23回カジュアルトーク開催のお知らせ」</a>を更新いたしました。'

-
  time:
    '2017-04-06'
  update:
    '<a href="http://wbawakate.jp/posts/events/21th/">【2017-03-20】　「第21回カジュアルトーク開催のお知らせ」</a>を更新いたしました。'

# li
#   | 2017.5.4
#   br
#   a(href="http://wbawakate.jp/posts/events/23th/") 【2017.4.28】　「第23回カジュアルトーク開催のお知らせ」
#   | を更新いたしました。
# li
#   | 2017.5.4
#   br
#   a(href="http://wbawakate.jp/posts/events/22th/") 【2017.3.31】　「第22回カジュアルトーク開催のお知らせ」
#   | を更新いたしました。
# li
#   | 2017.4.6
#   br
#   a(href="http://wbawakate.jp/posts/events/21th/") 【2017.3.20】　「第21回カジュアルトーク開催のお知らせ」
#   | を更新いたしました。
# li
#   | 2016.2.6
#   br
#   a(href="http://wbawakate.jp/posts/events/2017newyearparty/") 【2017.1.28】　「WBA若手の会　新年会」
#   | を更新いたしました。
# li
#   | 2016.12.6
#   br
#   a(href="http://wbawakate.jp/posts/events/19th/") 【2016.11.30】　「第19回カジュアルトーク開催のお知らせ」
#   | を更新いたしました。
# li
#   | 2016.11.18
#   br
#   a(href="http://wbawakate.jp/posts/events/18th/") 【2016.11.18】　「第18回カジュアルトーク開催のお知らせ」
#   | を更新いたしました。
# li
#   | 2016.11.12
#   br
#   a(href="http://wbawakate.jp/posts/events/17th/") 【2016.11.13】　「第17回カジュアルトーク」
#   | の動画と資料を公開致しました。
# li
#   | 2016.07.26
#   br
#   a(href="http://wbawakate.jp/posts/events/16th/") 【2016.07.29】　「第16回カジュアルトーク」
#   | の動画と資料を公開致しました。
# li
#   | 2016.06.05
#   br
#   a(href="http://wbawakate.jp/posts/events/14th/") 【2016.06.04】　「第12回 カジュアルトーク」
#   | の動画と資料を公開致しました。
# li
#   | 2016.05.21
#   br
#   a(href="http://wbawakate.jp/posts/events/data2/") 【2016.04.16】　「第2回 データ解析くらぶ」
#   | の動画と資料を公開致しました
# li
#   | 2016.05.05
#   br
#   a(href="http://wbawakate.jp/posts/events/%E7%AC%AC1%E5%9B%9E%E3%80%80%E3%83%87%E3%83%BC%E3%82%BF%E8%A7%A3%E6%9E%90%E3%81%8F%E3%82%89%E3%81%B6/") 【2016.04.16】　「第1回 データ解析くらぶ」
#   | の動画と資料を公開致しました
# li
#   | 2016.04.01
#   br
#   a(href="http://wbawakate.jp/posts/events/13th/") 【2016.03.08】　「第13回勉強会  『言語と画像の表現学習』 」
#   | の動画と資料を公開致しました
# li
#   | 2016.03.06
#   br
#   a(href="http://wbawakate.jp/posts/events/lady2/") 【2016.02.11】　「第2回 WBA若手の会 女子会＠下北沢 」
#   | の動画を公開致しました
# li
#   | 2016.02.28
#   br
#   a(href="http://wbawakate.jp/posts/events/12th/") 【2016.02.07】　「第12回 カジュアルトーク」
#   | の動画と資料を公開致しました。
# li
#   | 2016.02.10
#   br
#   a(href="http://wbawakate.jp/posts/events/event_004/") 「株式会社dwango 『CGIプロジェクト』インターン募集のお知らせ」
#   | を更新致しました。
# li
#   | 2016.02.03
#   br
#   a(href="http://wbawakate.jp/posts/events/event_003/") 【2016.02.19】　「株式会社UBIC主催　第2回学生向けセミナーのお知らせ」
#   | を更新致しました。
# li
#   | 2016.02.03
#   br
#   a(href="http://wbawakate.jp/posts/events/event_002/") 【2016.02.24~26】　「株式会社UBIC主催 技術職(R&D/開発) インターンシップのお知らせ」
#   | を更新致しました。
# li
#   | 2016.01.28
#   br
#   a(href="http://wbawakate.jp/posts/events/12th/") 【2016.02.07】　「第12回 カジュアルトーク開催のお知らせ」
#   | を更新致しました。
# li
#   | 2016.01.19
#   br
#   a(href="http://wbawakate.jp/posts/events/2016newyearparty/") 【2016.01.09】　「2016年 WBA若手の会 新年会」
#   | を更新致しました。
# li
#   | 2016.01.18
#   br
#   a(href="http://wbawakate.jp/posts/events/12th/") 【2016.02.07】　「第12回　カジュアルトーク開催のお知らせ」
#   | を更新致しました。
# li
#   | 2016.01.18
#   br
#   a(href="http://wbawakate.jp/posts/events/1stgirls/") 【2015.12.10】　「第1回　WBA若手の会 for girls」
#   | を更新致しました。
# li
#   | 2015.12.24
#   br
#   a(href="http://wbawakate.jp/posts/events/2016%e5%b9%b4%e3%80%80%e6%96%b0%e5%b9%b4%e4%bc%9a/") 【2016.01.09】　「2016年WBA若手の会新年会開催のお知らせ」
#   | を更新致しました。
# li
#   | 2015.12.22
#   br
#   a(href="http://wbawakate.jp/posts/events/event_001/") 【2016.01.20】　「株式会社UBIC主催　学生向けセミナーのお知らせ」
#   | を更新致しました。
# li
#   | 2015.12.10
#   br
#   | 【2015.12.16】　関東代表の
#   a(href="http://wbawakate.jp/yagi_takuma/", target="_blank") 八木
#   | と
#   a(href="http://wbawakate.jp/doi_yurika/", target="_blank") 土井
#   | が
#   a(href="http://www.sig-agi.org/sig-agi/events/sig-agi-01", target="_blank") 第1回人工知能学会 汎用人工知能研究会(SIG-AGI)
#   | において発表致します。
#   br
#   | “CNN-LSTMを用いた手話認識システムの開発”
# li
#   | 2015.12.10
#   br
#   | 【2015.12.16】  社会人支部代表の
#   a(href="http://wbawakate.jp/ashihara_yuta/", target="_blank") 芦原
#   | が
#   a(href="http://www.sig-agi.org/sig-agi/events/sig-agi-01", target="_blank") 第1回人工知能学会 汎用人工知能研究会(SIG-AGI)
#   | において発表致します。
#   br
#   | “CNN型AEとベクトル付加LSTMを用いた，物体の回転画像の想起モデル”
# li
#   | 2015.11.20
#   br
#   | 【2015.11.06】  代表の
#   a(href="http://wbawakate.jp/osawa_masahiko/", target="_blank") 大澤
#   | がInternational Symposium on Advanced Intelligent Systems (ISIS2015)において
#   strong Best Presentation Award
#   |  を受賞致しました。
# li
#   | 2015.11.20
#   br
#   | 【2015.11.06】 代表の
#   a(href="http://wbawakate.jp/osawa_masahiko/", target="_blank") 大澤
#   | がInternational Symposium on Advanced Intelligent Systems (ISIS2015)において発表致しました。
#   br
#   | “Image Impression Estimation without Image Processing,”
# li
#   | 2015.11.20
#   br
#   | 【2015.11.06】  代表の
#   a(href="http://wbawakate.jp/osawa_masahiko/", target="_blank") 大澤
#   | がInternational Symposium on Advanced Intelligent Systems (ISIS2015)において発表致しました。
#   br
#   | “A Learning Method for Echo State Networks Using RBM,”
# li
#   | 2015.09.30
#   br
#   | 【2015.09.03】代表の
#   a(href="http://wbawakate.jp/osawa_masahiko/", target="_blank") 大澤
#   | が神経回路学会 第25回全国大会において発表いたしました。
#   br
#   | “中間記憶から長期記憶への転送モデル”
# li
#   | 2015.09.30
#   br
#   | 【2015.09.03】  運営役員の
#   a(href="http://wbawakate.jp/itaya_kotone/", target="_blank") 板谷
#   | が神経回路学会 第25回全国大会において発表いたしました。
#   br
#   | “認知コンピューティングのための汎用ソフトウェアプラットフォームの設計と開発”
# li
#   | 2015.09.25
#   br
#   | 【2015.09.02】代表の
#   a(href="http://wbawakate.jp/osawa_masahiko/", target="_blank") 大澤
#   | が神経回路学会 第25回全国大会において発表いたしました。
#   br
#   | “RBMを用いたEcho State Networkの結合荷重決定法”
# li
#   | 2015.08.30
#   br
#   | 【2015.06.01】  運営役員の
#   a(href="http://wbawakate.jp/itaya_kotone/", target="_blank") 板谷
#   | が人工知能学会 第29回全国大会において発表いたしました。
#   br
#   | “認知コンピューティングのための汎用ソフトウェアプラットフォームの設計と開発”
# li
#   | 2015.06.20
#   br
#   | 【2015.05.31】代表の
#   a(href="http://wbawakate.jp/osawa_masahiko/", target="_blank") 大澤
#   | が人工知能学会 第29回全国大会において発表いたしました。
#   br
#   | “海馬-大脳新皮質系に着目した深層学習による記憶モデルの提案”
# li
#   | 2015.04.10
#   br
#   | 【2015.03.24】  会計の
#   a(href="http://wbawakate.jp/kawasaki_yusuke-2/", target="_blank") 川崎
#   | が法政大学理工学部応用情報工学科　卒業研究最優秀発表賞を受賞しました。
#   br
#   | ”Convolutional Neural Networksを用いた植物病害自動診断支援システムの開発”
# li
#   | 2015.03.24
#   br
#   | 【2015.03.23】 代表の大澤が慶應義塾大学平成26年度表彰学生に選出されました。今年は平成26年度の卒業生約6500人の中から22名が表彰を受け、副賞として金時計が授与されました。
# li
#   | 2015.03.18
#   br
#   | 【2015.03.18】 全脳アーキテクチャ若手の会主催による第5回ニコニコ生放送を開催いたします。講演者：川崎雄介　題目：強化学習 [勉強会ページ]
# li
#   | 2015.03.16
#   br
#   | 【2015.03.16】代表の大澤がIEEE Japan Chapter Young Researcher Awardを受賞しました。受賞題目：”RBMの学習特性の分析と隠れ層ニューロン数の自動決定法”
# li
#   | 2015.03.16
#   br
#   | 【2015.03.16】 代表の大澤が電子情報通信学会ニューロコンピューティング研究会で研究発表しました。”RBMにおける未学習データ検出法の提案と追加学習への応用”
# li
#   | 2015.03.12
#   br
#   | 【2015.03.12】 副代表の島田が電子情報通信学会総合大会（於：立命館大学）で研究発表しました。”Convolutional Neural Networksによる聴講者の授業への集中度推定”
# li
#   | 2015.03.12
#   br
#   | 【2015.03.12】 会計の川崎が電子情報通信学会総合大会（於：立命館大学）で研究発表しました。”Convolutional Neural Networksを用いた植物病害自動診断支援システムの開発”

