list:
  -
    title: 'SponsorEvent'
    path: '/posts/category/sponsorevent/'
    dest: '/sponsor/'

  -
    title: '株式会社FRONTEO主催 セミナーのお知らせ'
    path: '/posts/furonteo20160825/'
    dest: '/'

  -
    title: 'アディッシュ株式会社　技術職インターン募集のお知らせ'
    path: '/posts/adish_2016intern/'
    dest: '/'

  -
    title: '株式会社UBIC主催　第2回学生向けセミナーのお知らせ'
    path: '/posts/ubic20160219/'
    dest: '/'

  -
    title: '株式会社dwango　『CGIプロジェクト』インターン募集のお知らせ'
    path: '/posts/dwango20160506/'
    dest: '/'

  -
    title: '株式会社UBIC主催　技術職(R&D/開発) インターンシップのお知らせ'
    path: '/posts/ubic20160203/'
    dest: '/'

  -
    title: '株式会社UBIC主催　学生向けセミナーのお知らせ'
    path: '/posts/ubic20160120/'
    dest: '/'

  -
    title: 'About'
    path: '/about_us/'
    dest: '/about/'

  -
    title: 'About'
    path: '/_about_us/'
    dest: '/about/'

  # -
  #   title: 'Sponsor'
  #   path: '/sponsor/'
  #   dest: '/'

  # -
  #   title: 'スポンサーシップについて'
  #   path: '/about_sponsorship/'
  #   dest: '/'

  # -
  #   title: 'Contact'
  #   path: '/contact/'
  #   dest: '/'

  # -
  #   title: 'Member'
  #   path: '/member/'
  #   dest: '/'

  # -
  #   title: '三浦拓也'
  #   path: '/member/miura_takuya/'
  #   dest: '/'

  # -
  #   title: '上乃 聖'
  #   path: '/member/ueno_sei/'
  #   dest: '/'

  # -
  #   title: '中村 晃貴'
  #   path: '/member/koki_nakamura/'
  #   dest: '/'

  # -
  #   title: '中村健太郎'
  #   path: '/member/nakamura_kentaro/'
  #   dest: '/'

  # -
  #   title: '亀田 重幸'
  #   path: '/member/kameda_shigeyuki/'
  #   dest: '/'

  # -
  #   title: '佐藤 太一'
  #   path: '/member/taichi_sato/'
  #   dest: '/'

  # -
  #   title: '八木 拓真'
  #   path: '/member/yagi_takuma/'
  #   dest: '/'

  # -
  #   title: '加治屋 里奈'
  #   path: '/member/rina_kajiya/'
  #   dest: '/'

  # -
  #   title: '原衛 直子'
  #   path: '/member/harae_naoko/'
  #   dest: '/'

  # -
  #   title: '土井 ゆりか'
  #   path: '/member/doi_yurika/'
  #   dest: '/'

  # -
  #   title: '坂井 美帆'
  #   path: '/member/sakai_miho/'
  #   dest: '/'

  # -
  #   title: '増山 七海　'
  #   path: '/member/masuyama_nanami/'
  #   dest: '/'

  # -
  #   title: '大澤正彦'
  #   path: '/member/osawa_masahiko/'
  #   dest: '/'

  # -
  #   title: '岩淵 勇樹'
  #   path: '/member/iwabuchi_yuuki/'
  #   dest: '/'

  # -
  #   title: '島田大樹'
  #   path: '/member/shimada_daiki-2/'
  #   dest: '/'

  # -
  #   title: '川崎雄介'
  #   path: '/member/kawasaki_yusuke-2/'
  #   dest: '/'

  # -
  #   title: '廣芝和之'
  #   path: '/member/hiroshiba_kazuyuki/'
  #   dest: '/'

  # -
  #   title: '松岡 佑磨'
  #   path: '/member/matsuoka_yuma/'
  #   dest: '/'

  # -
  #   title: '板谷琴音'
  #   path: '/member/itaya_kotone/'
  #   dest: '/'

  # -
  #   title: '柿原 祥之'
  #   path: '/member/kakihara_yoshiyuki/'
  #   dest: '/'

  # -
  #   title: '永山 大志'
  #   path: '/member/nagayama_taishi/'
  #   dest: '/'

  # -
  #   title: '永田祥平'
  #   path: '/member/nagata_shohei/'
  #   dest: '/'

  # -
  #   title: '清丸 寛一'
  #   path: '/member/kiyomaru_hirokazu/'
  #   dest: '/'

  # -
  #   title: '田村陵大'
  #   path: '/member/tamura_ryota/'
  #   dest: '/'

  # -
  #   title: '神野成海'
  #   path: '/member/kanno_narumi/'
  #   dest: '/'

  # -
  #   title: '竹田卓也'
  #   path: '/member/takeda_takuya/'
  #   dest: '/'

  # -
  #   title: '芦原佑太'
  #   path: '/member/ashihara_yuta/'
  #   dest: '/'

  # -
  #   title: '藤田 恵梨香'
  #   path: '/member/fujita_erika/'
  #   dest: '/'

  # -
  #   title: '西田圭吾'
  #   path: '/member/nisida_keigo/'
  #   dest: '/'

  # -
  #   title: '都築拓'
  #   path: '/member/thuzuki_taku/'
  #   dest: '/'

  # -
  #   title: '門前 一馬'
  #   path: '/member/kadomae_kazuma/'
  #   dest: '/'

  # -
  #   title: 'Sitemap'
  #   path: '/sitemap/'
  #   dest: '/'
