-
  name:
    株式会社FRONTEO主催 セミナーのお知らせ
  image:
    'https://i1.wp.com/wbawakate.jp/wp-content/uploads/2016/08/FRONTEO.jpg?resize=505%2C260'
  link:
    'http://wbawakate.jp/posts/furonteo20160825/'

-
  name:
    アディッシュ株式会社　技術職インターン募集のお知らせ
  image:
    'https://i1.wp.com/wbawakate.jp/wp-content/uploads/2016/08/adish.jpg?resize=505%2C260'
  link:
    'http://wbawakate.jp/posts/adish_2016intern/'

-
  name:
    株式会社UBIC主催　第2回学生向けセミナーのお知らせ
  image:
    'https://i1.wp.com/wbawakate.jp/wp-content/uploads/2016/02/ubic.jpg?resize=505%2C260'
  link:
    'http://wbawakate.jp/posts/ubic20160219/'

-
  name:
    株式会社dwango　『CGIプロジェクト』インターン募集のお知らせ
  image:
    'https://i2.wp.com/wbawakate.jp/wp-content/uploads/2016/02/DWANGO.jpg?resize=505%2C260'
  link:
    'http://wbawakate.jp/posts/dwango20160506/'
