-
  name:
    株式会社ドワンゴ
  url:
    'http://dwango.co.jp/'
  image:
    dwango.png

-
  name:
    株式会社クロスコンパス・インテリジェンス
  url:
    'http://www.xcompass.com/'
  image:
    xcompass.png

-
  name:
    adish
  url:
    'http://www.adish.co.jp/'
  image:
    adish.png

-
  name:
    FRONTEO
  url:
    'http://www.fronteo.com/'
  image:
    fronteo.png

-
  name:
    ソフトバンク
  url:
    'http://www.softbank.jp/'
  image:
    softbank.png

-
  name:
    株式会社エクサインテリジェンス
  url:
    'http://exaintelligence.jp/'
  image:
    exaintelligence.png

-
  name:
    日経
  url:
    'http://www.nikkei.com/'
  image:
    nikkei.png

-
  name:
    カラフル・ボード株式会社
  url:
    'http://www.colorful-board.com/'
  image:
    sensy.png

-
  name:
    株式会社アニノベーション
  url:
    'http://aninnovation.co.jp/'
  image:
    aninnovation.png

-
  name:
    ソフトプラネット
  url:
    'http://www.softplanet.co.jp/'
  image:
    softplanet.png

-
  name:
    株式会社ウェルモ
  url:
    'http://www.welmo.co.jp/'
  image:
    welmo.png
