-
  type:
    カジュアルトーク
  name:
    第23回 カジュアルトーク
  image:
    'http://wbawakate.jp/wp-content/uploads/2017/05/Top-photo021-505x420.jpg'
  link:
    '23th.html'

-
  type:
    カジュアルトーク
  name:
    第22回 カジュアルトーク
  image:
    'http://wbawakate.jp/wp-content/uploads/2017/05/Top-photo03-505x420.jpg'
  link:
    '22th.html'

-
  type:
    カジュアルトーク
  name:
    第21回 カジュアルトーク
  image:
    'http://wbawakate.jp/wp-content/uploads/2017/05/Top-photo-505x420.jpg'
  link:
    '21th.html'

-
  type:
    カジュアルトーク
  name:
    第20回 カジュアルトーク
  image:
    'http://wbawakate.jp/wp-content/uploads/2017/02/01-505x420.jpg'
  link:
    '20th.html'
